const ROLE = {
  ADMIN: 1,
  TENANT: 2,
  PROPERTY_MANAGER: 3,
  OWNER: 4
};

const APPROVAL_RULES = {
  [ROLE.TENANT]: [ROLE.OWNER, ROLE.PROPERTY_MANAGER],
  [ROLE.PROPERTY_MANAGER]: [ROLE.OWNER, ROLE.ADMIN],
  [ROLE.OWNER]: [ROLE.ADMIN],
  [ROLE.ADMIN]: [ROLE.ADMIN] 
};

module.exports = { ROLE, APPROVAL_RULES };
